# Generated by Django 4.2 on 2024-10-03 11:30

from django.db import migrations, models
import restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(default=restaurant.models.genUUid, editable=False, max_length=8),
        ),
    ]
